### PR TITLE
Increased deployment target to iOS 9 for Xcode 12 support

### PR DESCRIPTION
**Pull request by ttimpe**
Increased deployment target to iOS 9 for Xcode 12 support

### CODE REVIEW

**Comment by ttimpe** [comment]
@googlebot I signed it!

**Comment by thomasvl** [comment]
What's the error/warning you hit?  I'm guessing this likely means we should update the podspec also to the same min version to support Xcode 12?

**Comment by ttimpe** [comment]
Yes I guess the podspec needs to be updated as well. Xcode 12 only supports deployment targets higher or equal to iOS 9.

**Comment by alak** [comment]
Any news on this ?

**Comment by thomasvl** [comment]
Just waiting on an update PR that keeps the two packaging systems in sync.

**Comment by karimhm** [comment]
I believe it is better to have 2 `Package.swift` manifest files, one for Swift tools version 5.3 and one for Swift tools version 5.2. Since the code is compatible with iOS versions earlier than 9.0.

**Comment by thomasvl** [comment]
Actually, is this still needed after #202  But not listing anything, don't we just get the mins that Xcode wants to use?

**Comment by thomasvl** [comment]
Closing this since I believe by removing the entry things are fixed now.

**Pull request closed without merging**
