### PR TITLE
Add `DEFINES_MODULE` to support downstream usage of static libs

### LINKED ISSUE #384: GTMSessionFetcher cannot be integrated as static libraries with CocoaPods because it does not define a module (`DEFINES_MODULE`)
**Steps to reproduce**
1. [Install CocoaPods.](https://guides.cocoapods.org/using/getting-started.html#installation)
2.  In Xcode, make new iOS app project. 
2. cd into the directory and `pod init` to initialize CocoaPods.
3. In the generated `Podfile` comment out `use_frameworks!` to embed as static libs.  Add a pod that depends on `GTMSessionFetcher`, for example, `GTMAppAuth`:
```ruby
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'GTMAppAuth', '4.1.1'
```
5. Run `pod install`

**Result**
`pod install` fails:
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.7.3)
Installing GTMAppAuth (4.1.1)
Installing GTMSessionFetcher (3.3.2)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `GTMAppAuth` depends upon `GTMSessionFetcher` and `AppAuth`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

`GTMSessionFetcher` is not setting up a module, and doesn't have `DEFINES_MODULE` for that to be done automatically.

This can be fixed by adding `DEFINES_MODULE` to [GTMSessionFetcher.podspec](https://github.com/google/gtm-session-fetcher/blob/main/GTMSessionFetcher.podspec).  See [CocoaPods documentation about modular headers](https://blog.cocoapods.org/CocoaPods-1.5.0/#modular-headers).
```ruby
  s.xcconfig = {
     'DEFINES_MODULE' => 'YES',
  }
```

### PR DESCRIPTION
**Pull request by thomasvl**
Fixes #384

### CODE REVIEW

**Comment by thomasvl** [comment]
@paulb777 @mdmathias - this seem good?

**Comment by paulb777** [comment]
I can stage the modified podspec to https://github.com/firebase/SpecsStaging and make sure it doesn't impact Firebase tests - and let you know tomorrow.

**Comment by paulb777** [comment]
I staged a version (without visionOS) at https://github.com/firebase/SpecsStaging/commit/948fd05d791b8b019d927cffa76423b6059cfbeb cc:@ncooke3

**Comment by mdmathias** [comment]
I'm going to be making a similar change for [AppAuth-iOS](https://github.com/openid/AppAuth-iOS/issues/844).

**Comment by paulb777** [comment]
Firebase nightly tests look good with the gtm-session-fetcher podspec update - https://github.com/firebase/firebase-ios-sdk/issues/12669

**Comment by vonovak** [comment]
Hello and thanks for this fix 🙂

@thomasvl would it be possible to have this released soon?

There are downstream packages building on top of this, such as wrappers for Google Sign in SDK for React Native and maybe Flutter and others that are hitting #384 and having this published would make it easy to use the latest versions.

I'm aware that there are workaround that are not too complicated even, but requiring people to take extra steps, however easy and nicely documented means friction and questions in issue tracker.

Thank you 🙂

**Pull request merged**
